#-------------------------------------------------------------------------------
# Name:        KML to Layer Post-Processing

# Purpose:     Certain attribute fields contain information formatted as HTML tables
#              after running a 'KML to Layer' operation in ArcMap.This tool is designed
#              to parse the HTML in those fields and create new populated fields based
#              on the information in the HTML.
#
# Author:      Cameron McEvenue, Esri Canada
#
# Created:     20/03/2015
# Copyright:   (c) Cameron McEvenue, Esri Canada 2015

#-------------------------------------------------------------------------------


import arcpy, os, sys, time, datetime,traceback, numpy
from HTMLParser import HTMLParser


def postProcess(featureClass,htmlField,outWorkspace,outFC,UID_field):

    arcpy.env.workspace = outWorkspace
    arcpy.SetLogHistory(True)
    arcpy.env.overwriteOutput = True

    desc = arcpy.Describe(featureClass)

    #Create new feature class to populate with data from input feature class containing HTML
    #arcpy.CreateFeatureclass_management(outWorkspace,outFC,desc.shapeType.upper(),featureClass,"DISABLED","DISABLED",desc.spatialReference)

    fc = os.path.join(outWorkspace,outFC)

    fields = [UID_field, "FolderPath", htmlField]

    #Create list of unique field values for UID_field variable
    UID_list = arcpy.da.TableToNumPyArray(featureClass,UID_field)
    UID_list = numpy.unique(UID_list[UID_field])
    UID_list = UID_list.tolist()

##    for UID in UID_list:

##    where = '"' + UID_field + '" = ' + "'" + str(UID) + "'"
    where = '"' + UID_field + '" = ' + "'1'"
    for row in arcpy.da.SearchCursor(featureClass,fields, where):
        print row[1]



##    for row in arcpy.da.SearchCursor(fc,fields):
##        print row[2]

##def parseHTML(htmlBlock):
##
##    #Get the full path to the feature class generated by KML to Layer





##    inputFieldName = ""
##
##    arcpy.KMLToLayer_conversion(inputKML,arcpy.env.workspace)
##    print "Done"
##
##    arcpy.env.workspace = os.path.join(outputWorkspace,)

if __name__ == "__main__":

    # Gather inputs
##    featureClass = arcpy.GetParameterAsText(0)
##    htmlField = arcpy.GetParameterAsText(1)
##    outWorkspace = arcpy.GetParameterAsText(2)
##    outFC = arcpy.GetParameterAsText(3)
##    UID_field = arcpy.GetParameterAsText(4)
    featureClass = r"D:\SIDE_PROJECTS\K_26_Mississauga_GF_Wardv3.gdb\Placemarks\Polygons"
    htmlField = "PopupInfo"
    outWorkspace= r"D:\SIDE_PROJECTS\K_26_Mississauga_GF_Wardv3.gdb"
    outFC = "test"
    UID_field = "Name"
    postProcess(featureClass,htmlField,outWorkspace,outFC,UID_field)